apps/cars/urls.py
from django.conf.urls import patterns, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = patterns(
    '',
    url(r'^$', 'cars.views.main', name='main'),
)
urlpatterns += staticfiles_urlpatterns()

fortytwo_test_task/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^', include('apps.hello.urls')),
    url(r'^cars/', include('apps.cars.urls')),
    url(r'^admin/', include(admin.site.urls)),
    (r'^uploads/(?P<path>.*)$', 'django.views.static.serve',
                                {'document_root': settings.MEDIA_ROOT}),
    url(r'', include('social_auth.urls')),
    url(r'^ytube/', include('apps.ytget.urls')),
)
urlpatterns += staticfiles_urlpatterns()

apps/cars/models.py
from django.db import models

# Create your models here.


class Car(models.Model):
    ALFA_ROMEO, BMW, LANCIA, MERCEDES_BENZ, OPEL, PORSCHE = range(1, 7)
    BRAND_CHOICES = (
        (ALFA_ROMEO, 'Alfa Romeo'),
        (BMW, 'BMW'),
        (LANCIA, 'Lancia'),
        (MERCEDES_BENZ, 'Mercedes-Benz'),
        (OPEL, 'Opel'),
        (PORSCHE, 'Porsche'),
        )
    CABRIO, COUPE, SUV, LIMOUSINE, KOMBI, VAN, TRANSPORTER = range(1, 8)
    CONSTRACTION_CHOICES = (
        (CABRIO, 'Cabrio'),
        (COUPE, 'Coupe'),
        (SUV, 'SUV'),
        (LIMOUSINE, 'Limousine'),
        (KOMBI, 'Kombi'),
        (VAN, 'VAN'),
        (TRANSPORTER, 'Transprter'),
        )
    MANUAL, AUTHOMATIC = range(1, 3)
    TRANS_CHOICES = (
        (MANUAL, 'Manual'),
        (AUTHOMATIC, 'Authomatic'),
        )
    brand = models.PositiveIntegerField(choices=BRAND_CHOICES)
    construction = models.PositiveIntegerField(choices=CONSTRACTION_CHOICES)
    model = models.CharField(max_length=15)
    used = models.BooleanField(blank=True, default=False)
    demonstration = models.BooleanField(blank=True, default=False)
    ez = models.DateField(blank=True, null=True)
    mileage = models.IntegerField(default=0)
    power = models.PositiveIntegerField(blank=True, null=True)
    price = models.PositiveIntegerField(blank=True, null=True)
    transmission = models.PositiveIntegerField(choices=TRANS_CHOICES)
    color = models.CharField(max_length=15)
    main_photo = models.ImageField(upload_to='photo', null=True, blank=True)
    photo_back = models.ImageField(upload_to='photo', null=True, blank=True)
    photo_wheel = models.ImageField(upload_to='photo', null=True, blank=True)
    photo_left = models.ImageField(upload_to='photo', null=True, blank=True)
    photo_right = models.ImageField(upload_to='photo', null=True, blank=True)
    photo_back_sit = models.ImageField(upload_to='photo',
                                       null=True,
                                       blank=True)
    photo_head = models.ImageField(upload_to='photo', null=True, blank=True)
    photo_rudder = models.ImageField(upload_to='photo', null=True, blank=True)
    photo_player = models.ImageField(upload_to='photo', null=True, blank=True)
    photo_monitour = models.ImageField(upload_to='photo',
                                       null=True,
                                       blank=True)
    photo_door = models.ImageField(upload_to='photo', null=True, blank=True)
    photo_location = models.ImageField(upload_to='photo',
                                       null=True,
                                       blank=True)
    photo_info = models.ImageField(upload_to='photo', null=True, blank=True)
    photo_shop = models.ImageField(upload_to='photo', null=True, blank=True)
    photo_advertisement = models.ImageField(upload_to='photo',
                                            null=True, blank=True)

apps/cars/views.py
from django.shortcuts import render
from django.contrib.auth.models import User
from cars.models import Car

# Create your views here.


def main(request):
    br = []
    for i in range(1, Car.objects.count()+1):
        if i % 4 == 0:
            br.append(i)
    return render(request, 'cars/cars.html', {'cars': Car.objects.all(),
                  'br': br})


def superuser(request):
    User.objects.create(username='admin', is_admin=True)
    user = User.objects.get(username='admin')
    user.set_password('admin')

templates/cars/cars.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Cars</title>

        <meta http-equiv="X-UA-Compatible" content="chrome=IE7" />

        <meta name="viewport" content="initial-scale=1.0, width=device-width"/>
        <meta name="apple-mobile-web-app-capable" content="yes"/>
        <meta name="apple-mobile-web-app-status-bar-style" content="black" />
        <link rel="stylesheet" href="{% static 'css/cars/screen.css' %}" media="screen, projection"/>
        <link rel="stylesheet" href="{% static 'css/cars/swiper.min.css' %}" media="screen, projection"/>
        <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
        <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
        <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
        <script src="https://raw.githubusercontent.com/furf/jquery-ui-touch-punch/master/jquery.ui.touch-punch.min.js"></script>
        <script src="{% static 'js/jquery.carouFredSel-6.0.4-packed.js' %}"></script>


    <script type="text/javascript">
        $(function() {
            var width = $("#first").attr("width");
            var height = $("#first").attr("height");
            z = width/height;
            $("#slider").slider({
            orientation: "horizontal",
            min: 240,
            max: 640,
            value: width,
            slide: function(event, ui) {
            y = Math.round(ui.value/z);
            $("#amount").val(ui.value);
            $("#amount2").val(y);
            $('.images').width(ui.value);
            $('.images').height(y);
            }
            });
            $("#amount").attr('value',width);
            $("#amount2").attr('value',height);
            });
    </script>
  
    </head>
    <body id="body" class="">
    <label for="amount">Width:</label>
    <input type="text" id="amount" value="" style="border:0; width:30px; color:#f6931f; font-weight:bold;" />
    <label for="amount2">Height:</label>
    <input type="text" id="amount2" value="" style="border:0; width:30px; color:#f6931f; font-weight:bold;" />

    <div id="slider" style="height:6px; width:220px; margin: 10px; "></div>

    <div id="cars">
        {% for car in cars %}
            <script>
                $( function() {
                    $( "#dialog-{{ car.pk }}" ).dialog({
                        autoOpen: false,
                        height: $(window).height()*0.85,
                        width: $(window).width()*0.85,
                        show: {
                            effect: "clip",
                            duration: 1000
                        },
                        hide: {
                            effect: "clip",
                            duration: 1000
                        }
                    });
                    $(".ui-dialog-content").css({'background-color':'whitesmoke'});

                } );
            </script>
        {% if forloop.counter == 1 %}
        <br />
        <div class="illustrations">
            <img id='first' ondblclick='$("#dialog-{{ car.pk }}").dialog( "open");' class='images'src="{% static 'images/default.png' %}" width="640" height="480" realsrc="{{ MEDIA_URL }}{{ car.main_photo }}">

        </div>
        {% else %}

        <div class="illustrations">
        <img ondblclick='$("#dialog-{{ car.pk }}").dialog( "open");'class='images'src="{% static 'images/default.png' %}" width="640" height="480" realsrc="{{ MEDIA_URL }}{{ car.main_photo }}">

        </div>
        {% endif %}

        <div id="dialog-{{ car.pk }}" title="{{ car.get_brand_display }} {{ car.model }}" width="85vw">
            <div class="swiper-container">
                <div class="swiper-wrapper">
                    {% if car.main_photo %}
                    <div class="swiper-slide"><img width="480" height='320' src="{{ MEDIA_URL }}{{ car.main_photo }}" alt=""></div>
                    {% endif %}
                    {% if car.photo_back %}
                    <div class="swiper-slide"><img width="480" height='320'  src="{{ MEDIA_URL }}{{ car.photo_back }}" alt=""></div>
                    {% endif %}
                    {% if car.photo_wheel %}
                    <div class="swiper-slide"><img width="480" height='320' src="{{ MEDIA_URL }}{{ car.photo_wheel }}" alt=""></div>
                    {% endif %}
                    {% if car.photo_left %}
                    <div class="swiper-slide"><img width="480" height='320' src="{{ MEDIA_URL }}{{ car.photo_left }}" alt=""></div>
                    {% endif %}
                    {% if car.photo_right %}
                    <div class="swiper-slide"><img width="480" height='320' src="{{ MEDIA_URL }}{{ car.photo_right }}" alt=""></div>
                    {% endif %}
                    {% if car.photo_back_sit %}
                    <div class="swiper-slide"><img width="480" height='320' src="{{ MEDIA_URL }}{{ car.photo_back_sit }}" alt=""></div>
                    {% endif %}
                    {% if car.photo_head %}
                    <div class="swiper-slide"><img width="480" height='320' src="{{ MEDIA_URL }}{{ car.photo_head }}" alt=""></div>
                    {% endif %}
                    {% if car.photo_rudder %}
                    <div class="swiper-slide"><img width="480" height='320' src="{{ MEDIA_URL }}{{ car.photo_rudder }}" alt=""></div>
                    {% endif %}
                    {% if car.photo_player %}
                    <div class="swiper-slide"><img width="480" height='320' src="{{ MEDIA_URL }}{{ car.photo_player }}" alt=""></div>
                    {% endif %}
                    {% if car.photo_monitour %}
                    <div class="swiper-slide"><img width="480" height='320' src="{{ MEDIA_URL }}{{ car.photo_monitour }}" alt=""></div>
                    {% endif %}
                    {% if car.photo_door %}
                    <div class="swiper-slide"><img width="480" height='320' src="{{ MEDIA_URL }}{{ car.photo_door }}" alt=""></div>
                    {% endif %}
                    {% if car.photo_location %}
                    <div class="swiper-slide"><img width="480" height='320' src="{{ MEDIA_URL }}{{ car.photo_location }}" alt=""></div>
                    {% endif %}
                    {% if car.photo_info %}
                    <div class="swiper-slide"><img width="480" height='320' src="{{ MEDIA_URL }}{{ car.photo_info }}" alt=""></div>
                    {% endif %}
                    {% if car.photo_shop %}
                    <div class="swiper-slide"><img width="480" height='320' src="{{ MEDIA_URL }}{{ car.photo_shop }}" alt=""></div>
                    {% endif %}
                    {% if car.photo_advertisement %}
                    <div class="swiper-slide"><img width="480" height='320' src="{{ MEDIA_URL }}{{ car.photo_advertisement }}" alt=""></div>
                    {% endif %}

                </div>
                <div class="swiper-pagination"></div>
            </div>
            <div class="info">
            <table class='details'>
                <tr><td>Construction</td><td>{{ car.construction }}</td></tr>
                <tr><td>EZ</td><td>{{ car.ez }}</td></tr>
                <tr><td>Mileage</td><td>{{ car.mileage }}</td></tr>
                <tr><td>Power</td><td>{{ car.power  }}</td></tr>
                <tr><td>Transmission</td><td>{{ car.transmission }}</td></tr>
                <tr><td>Color</td><td>{{ car.color }}</td></tr>
                <tr><td>Construction</td><td>{{ car.construction }}</td></tr>
                <tr><td>Construction</td><td>{{ car.construction }}</td></tr>
            </table>
            </div>
        </div>
        {% if forloop.counter in br %}
            <br />
        {% endif %}
        {% endfor %}
    </div>

    <script src="{% static 'js/drag.js' %}"></script>
    </body>

  <script>
    function isVisible(elem) {

      var coords = elem.getBoundingClientRect();

      var windowHeight = document.documentElement.clientHeight;
      var windowWidth = document.documentElement.clientWidth;


      var topVisible = coords.top > 0 && coords.top < windowHeight;
      var bottomVisible = coords.bottom < windowHeight && coords.bottom > 0;
      var leftVisible = coords.left > 0 && coords.left < windowWidth;
      var rightVisible = coords.left > 0 && coords.left < windowWidth;

      return topVisible && leftVisible || bottomVisible && rightVisible;
    }

    function inWindow(s){
      var scrollTop = $(window).scrollTop();
      var windowHeight = $(window).height();
      var currentEls = $(s);
      var result = [];
      currentEls.each(function(){
        var el = $(this);
        var offset = el.offset();
        if(scrollTop <= offset.top && (el.height() + offset.top) < (scrollTop + windowHeight))
          result.push(this);
      });
      return $(result);
    }

    function showVisible() {
      var imgs = document.getElementsByTagName('img');
      for (var i = 0; i < imgs.length; i++) {

        var img = imgs[i];

        var realsrc = img.getAttribute('realsrc');
        if (!realsrc) continue;

        if (isVisible(img)) {
          img.src = realsrc;
          img.setAttribute('realsrc', '');
        }
      }

    }

    window.document.getElementById("body").style.width = {{ count }}
    window.onscroll = showVisible;
    window.onmouseup = showVisible;
    $( window.document ).ready(function() {
       showVisible();

    });
  </script>
  <script src="{% static 'js/swiper.min.js' %}"></script>

  <script>
  var swiper = new Swiper('.swiper-container', {
      pagination: '.swiper-pagination',
      paginationClickable: true,
  });

  </script>

</html>